### ISSUE TITLE
node stops work...

### ISSUE THREAD

**Issue by kovir** [justind000/nRF-IoT#1]
Hello
I tried this project - I have a base, one relay and two nodes. Problem is that after few hours ( sometimes after 20-30 minutes) one of the nodes stops to work - It can't send data to relay. after reset everything is OK until next transmission break...

any idea how to improve?

**Comment by justind000** [comment]
Hello. Are you still having that problem? I've had several nodes up and running for weeks with no issues.

**Comment by kkc430** [comment]
hai i got problem in node program like plz solve this problm 

node.ino: In function 'bool relay(HEADER, byte)':
node:160: error: no matching function for call to 'RF24::write(HEADER_, unsigned int, bool)'
node.ino:160:56: note: candidate is:
In file included from node.ino:3:0:
C:\Users\MMIC616\Documents\libraries\RF24-master/RF24.h:281:8: note: bool RF24::write(const void_, uint8_t)
   bool write( const void\* buf, uint8_t len );
        ^
C:\Users\MMIC616\Documents\libraries\RF24-master/RF24.h:281:8: note:   candidate expects 2 arguments, 3 provided
no matching function for call to 'RF24::write(HEADER*, unsigned int, bool)'
